env: standard
runtime: nodejs14
instance_class: F1

# handlers:
# - url: /(.*\..+)$
#   static_files: build/\1
#   upload: build/(.*\..+)$
# - url: /.*
#   static_files: build/index.html
#   upload: build/index.html

entrypoint: npm run server:prod

# default_expiration: "12h"

automatic_scaling:
  min_instances: 1
  max_idle_instances: 1
  max_instances: 2

network:
  session_affinity: true
  


