steps:
  - name: 'bash'
    args:
      - -c
      - |
        echo "$_ENV" > .env && \
        cat .env
  - name: 'bash'
    args: ['cat', '.env']
  - name: node:14-slim
    entrypoint: yarn
    args: ["install"]
  - name: node:14-slim
    entrypoint: yarn
    args: ["build"]
  
  # GCE Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['compute', 'scp', '--recurse', 'src', 'package.json', 'yarn.lock', 'root@$_GCE_INSTANCE_NAME:/usr/local/$PROJECT_ID/', '--zone', '$_GCE_INSTANCE_ZONE']

  # GAE Deploy
  - name: gcr.io/cloud-builders/gcloud
    args: ["app", "deploy", "app.yaml", "--project=$PROJECT_ID", "--quiet"]